### ISSUE TITLE
[Suggestion] Support for custom items (namespace + using custom model data)

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [PluginBugs/Issues-EpicBackpacks#75]
**Is your feature request related to a problem? Please describe.**
It would be great if we could define custom items in the plugin, for example in crafting recipes or when whitelisting/blacklisting items from certain backpacks.

**Describe the solution you'd like**
Allow us to define the use of custom items in the plugin outside of the backpack skins.
Areas of use: Backpack crafting recipes, Auto-pickup, Pre-filled backpacks, Whitelist/blacklist items.

**Describe alternatives you've considered**
I see that you can use "itemsadder" types so maybe that could be used instead of using namespaces (e.g. "type:  ITEM" and "material: itemsadder:some_item").
In either case, I think supporting custom model data would be ideal when handling other plugins not directly supported by EpicBackpacks.

**Additional context**
none

**Comment by LoneDev6** [comment]
ItemsAdder recipes will be supported when this request will be implemented: #31
About whitelisting/blacklisting ItemsAdder items, I implemented that in the upcoming update.

You can now for example write this:
```yml
  wood:
    enabled: true
    display_name: '&fWood Backpack'
    item:
      type: HEAD
      texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWFhMzY4MzY1YjYwMzM3NWQ1Y2RkYTlkYWE5MjRiOTY0YjFmMTE4YTcyNTAxODdhNjk2YTA3ZmYxOGNmMDIifX19'
    size: 5
    whitelist:
      - OAK_WOOD
      - SPRUCE_WOOD
      - my_items:custom_wood_block
```
