### ISSUE TITLE
[Suggestion] You could use other backpacks in the recipes

### ISSUE THREAD

**Issue by RitsuElAnti** [PluginBugs/Issues-EpicBackpacks#89]
Could you use other backpacks in the recipes, to give the sensation of improvements or upgrades?

<img width="264" alt="7fbb4063d55f817c82013395b6d93a26c2da2734" src="https://github.com/PluginBugs/Issues-EpicBackpacks/assets/119564188/1620f16d-1f47-4e54-90e4-ef5a9f6d4547">

This image is taken from other plugins, used as a reference, removing the spam from this

**Comment by LoneDev6** [comment]
Done!
Note: backpacks crafted with previous plugin versions won't work in recipes, you have to re-craft them.
They won't also work if you rename or change their lore.

example:
```yml
    craft_recipe:
      amount: 4
      pattern:
      - XOX
      - XEX
      - XOX
      ingredients:
        O: OBSIDIAN
        E: example_backpack_2
```



![Image](https://github.com/PluginBugs/Issues-EpicBackpacks/assets/27242001/9b03555a-ad03-42fa-8d2b-a43427886569)
